#pragma once
#include <cstdint>
#include <cstddef>

// AUTO-GENERATED by generate_pal_layout_profile_v8.py. Do not edit by hand.
// Required source: F:\Projs\PwProjESE\UpdateScript\CXXHeaderDump\Pal.hpp
// Required source: F:\Projs\PwProjESE\UpdateScript\CXXHeaderDump\Pal_enums.hpp
// Optional Actor_RootComponent source: F:\Projs\PwProjESE\UpdateScript\CXXHeaderDump\Engine.hpp
// Optional SceneComponent_RelativeLocation source: F:\Projs\PwProjESE\UpdateScript\CXXHeaderDump\Engine.hpp
// Optional SceneComponent_AttachParent source: F:\Projs\PwProjESE\UpdateScript\CXXHeaderDump\Engine.hpp
// Optional Transform_Translation source: F:\Projs\PwProjESE\UpdateScript\CXXHeaderDump\CoreUObject.hpp
namespace EseGeneratedPalLayout {
    static constexpr bool Has_BuildFingerprint = true;
    static constexpr std::uint32_t Build_TimeDateStamp = 0x6AA377C1;
    static constexpr std::uint32_t Build_SizeOfImage = 0x0A011000;
    static constexpr std::uint32_t Build_TextRva = 0x00001000;
    static constexpr std::uint32_t Build_TextSize = 0x067134F7;
    static constexpr std::uint64_t Build_TextHash = 0x47EA3AFF5784195Cull;

    static constexpr bool Has_UObject_OuterPrivate = false;
    static constexpr std::uintptr_t UObject_OuterPrivate = 0x0;
    static constexpr bool Has_Actor_RootComponent = true;
    static constexpr std::uintptr_t Actor_RootComponent = 0x198;
    static constexpr bool Has_SceneComponent_RelativeLocation = true;
    static constexpr std::uintptr_t SceneComponent_RelativeLocation = 0x128;
    static constexpr bool Has_SceneComponent_AttachParent = true;
    static constexpr std::uintptr_t SceneComponent_AttachParent = 0xB0;
    static constexpr bool Has_SceneComponent_ComponentToWorld = false;
    static constexpr std::uintptr_t SceneComponent_ComponentToWorld = 0x0;
    static constexpr bool Has_Transform_Translation = true;
    static constexpr std::uintptr_t Transform_Translation = 0x20;
    static constexpr bool Has_RootComponent_WorldLocation = false;
    static constexpr std::uintptr_t RootComponent_WorldLocation = 0x0;

    static constexpr std::uintptr_t DamageInfo_AttackElement = 0x30;
    static constexpr std::uintptr_t DamageInfo_EffectType1 = 0x90;
    static constexpr std::uintptr_t DamageInfo_EffectValue1 = 0x94;
    static constexpr std::uintptr_t DamageInfo_EffectType2 = 0x9C;
    static constexpr std::uintptr_t DamageInfo_EffectValue2 = 0xA0;
    static constexpr std::uintptr_t Character_CharacterParameterComponent = 0x630;
    static constexpr std::uintptr_t Character_StaticCharacterParameterComponent = 0x638;
    static constexpr std::uintptr_t Character_DamageReactionComponent = 0x640;
    static constexpr std::uintptr_t Character_StatusComponent = 0x648;
    static constexpr std::uintptr_t Character_VisualEffectComponent = 0x678;
    static constexpr std::uintptr_t CharacterParameter_ElementType1 = 0xD8;
    static constexpr std::uintptr_t CharacterParameter_ElementType2 = 0xD9;
    static constexpr std::uintptr_t StaticCharacterParameter_IsPal = 0x4A0;
    static constexpr std::uintptr_t StatusComponent_ExecutionStatusList = 0x110;
    static constexpr std::uintptr_t StatusBase_IsEndStatus = 0x48;
    static constexpr std::uintptr_t StatusBase_StatusID = 0x90;
    static constexpr std::uintptr_t StatusBase_Duration = 0xA4;
    static constexpr std::uintptr_t StatusBase_DurationTimer = 0xAC;
    static constexpr std::uintptr_t VisualEffectComponent_ExecutionVisualEffects = 0x120;
    static constexpr std::uintptr_t VisualEffectBase_IsEnd = 0x28;
    static constexpr std::uintptr_t VisualEffectBase_ID = 0x50;

    static constexpr std::uintptr_t StatusBase_NativeSize = 0xB0;

    static constexpr std::uint8_t Effect_Burn = 4;
    static constexpr std::uint8_t Effect_Wetness = 5;
    static constexpr std::uint8_t Effect_Freeze = 6;
    static constexpr std::uint8_t Effect_Electrical = 7;
    static constexpr std::uint8_t Effect_Muddy = 8;
    static constexpr std::uint8_t Effect_IvyCling = 9;
    static constexpr std::uint8_t Effect_Darkness = 10;
    static constexpr std::uint8_t Element_None = 0;
    static constexpr std::uint8_t Element_Normal = 1;
    static constexpr std::uint8_t Element_Fire = 2;
    static constexpr std::uint8_t Element_Water = 3;
    static constexpr std::uint8_t Element_Leaf = 4;
    static constexpr std::uint8_t Element_Electricity = 5;
    static constexpr std::uint8_t Element_Ice = 6;
    static constexpr std::uint8_t Element_Earth = 7;
    static constexpr std::uint8_t Element_Dark = 8;
    static constexpr std::uint8_t Element_Dragon = 9;
    static constexpr std::uint8_t Status_Burn = 19;
    static constexpr std::uint8_t Status_Wetness = 20;
    static constexpr std::uint8_t Status_Freeze = 21;
    static constexpr std::uint8_t Status_Electrical = 22;
    static constexpr std::uint8_t Status_Muddy = 23;
    static constexpr std::uint8_t Status_IvyCling = 24;
    static constexpr std::uint8_t Status_Darkness = 25;
    static constexpr std::uint8_t Status_VanillaWetFreeze = 59;
    static constexpr std::uint8_t Status_VanillaWetFreezeResist = 60;
    static constexpr std::uint8_t VisualEffect_IceCondition = 17;
}
